apiVersion: v2
name: dummypro
description: Helm chart for the DummyPro FastAPI application

type: application

version: 1.0.0

appVersion: "1.0.0"

keywords:
  - fastapi
  - python
  - kubernetes
  - helm

home: https://github.com/siddanthosalli99/dummyrepo

sources:
  - https://github.com/siddanthosalli99/dummyrepo

maintainers:
  - name: Siddant H