namespace: dummy

appName: dummypro

replicaCount: 2

deployment:
  name: dummypro-deployment

image:
  repository: mepointdexter/balls
  tag: latest
  pullPolicy: Always

containerPort: 8000

service:
  name: dummypro-service
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080